version: "3.1"

services:
  bank_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./docker/database.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
